// This file is auto-generated by `scripts/generate-portal-gates.js`.
// Do not edit this file directly. Edit the TSV instead:
// - res/data/portal_gates.tsv

export const portalGateMap = {
  "가평교육원": [
    {
      portalX: 42,
      portalY: 36,
      portalSize: 2,
      requiredItems: [
        "여권",
      ],
    },
  ]
} as const;
