// This file is auto-generated by `scripts/generate-inventory-remove-on-enter.js`.
// Do not edit this file directly. Edit the TSV instead:
// - res/data/inventory_remove_on_enter.tsv

export const inventoryRemoveOnEnterMap = {
  "종로길거리3": [
    "약봉투",
  ],
  "종로길거리6": [
    "전차표",
  ],
} as const;
