// This file is auto-generated by `scripts/generate-inventory-interactions.js`.
// Do not edit this file directly. Edit the TSV instead:
// - res/data/inventory_interactions.tsv

export const inventoryInteractionMap = {
  "gold_1": {
    earnItemList: [
      {
        name: "용의 머리",
        url: "https://rid.gcdn.ntruss.com/countries/gold_A.png",
      },
    ],
    mobileMessage: "용의 머리를 획득하였습니다.",
    pcMessage: "용의 머리를 획득하였습니다.",
    missingMessage: "",
  },
  "gold_2": {
    earnItemList: [
      {
        name: "용의 몸통",
        url: "https://rid.gcdn.ntruss.com/countries/gold_B.png",
      },
    ],
    mobileMessage: "용의 몸통를 획득하였습니다.",
    pcMessage: "용의 몸통를 획득하였습니다.",
    missingMessage: "",
  },
  "gold_3": {
    earnItemList: [
      {
        name: "용의 꼬리",
        url: "https://rid.gcdn.ntruss.com/countries/gold_C.png",
      },
    ],
    mobileMessage: "용의 꼬리를 획득하였습니다.",
    pcMessage: "용의 꼬리를 획득하였습니다.",
    missingMessage: "",
    prerequisiteItemList: [
    ],
  },
} as const;
